name: LobbyCore
main: LC\LobbyCore
version: 1.2.0
api: 5.0.0
author: JuanantonioVYT

commands:
  hub:
    description: Hub command
    permission: lobbycore.command.hub

permissions:
  lobbycore.command.hub:
    default: true
