name: LobbyCore
main: RassyaYa\LobbyCore
version: 1.0.0
api: 5.0.0
author: RassyaYa

commands:
  hub:
    description: Hub command
    permission: lobbycore.command.hub

permissions:
  lobbycore.command.hub:
    default: true
